### ISSUE TITLE
incorrect call to 'get' in get_rewards()

### ISSUE THREAD

**Issue by gdbassett** [teamrevlo/revlo-python-client#3]
for r in client.get_rewards():
    print r
    

AttributeErrorTraceback (most recent call last)
<ipython-input-74-89970528145e> in <module>()
----> 1 for r in client.get_rewards():
      2     print r
      3 

/usr/local/lib/python2.7/site-packages/revlo/client.pyc in get_rewards(self)
     57 
     58   def get_rewards(self):
---> 59     response = self._get('{}/{}/rewards'.format(self.base_url, VERSION))
     60     total = response['total']
     61     page_size = response['page_size']

AttributeError: 'RevloClient' object has no attribute '_get'

**Comment by scottnguyen** [comment]
Oops. Fixed this. Upgrade the package for the latest changes.
