### ISSUE TITLE
get_rewards() and pages

### ISSUE THREAD

**Issue by gdbassett** [teamrevlo/revlo-python-client#4]
It is unclear how get_rewards handles pages.  From the code it appears to iterate through all pages.  It could potentially take a page argument with the default being to iterate through all pages.

**Comment by scottnguyen** [comment]
not a bad idea. another idea could be position=int and it figures out the page and everything internally. From a user's perspective, they don't have to understand the pagination detail.

EDIT: Actually, never mind. That probably belongs on the service-side of things. The latest version (0.15.3) should facilitate for optional params. Run `pip install revlo --upgrade` to receive the update.
